apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  name: testing
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: testing project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: testing
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      files:
      - path: apps/**/testing/config.yaml
      repoURL: https://github.com/TheCodingSheikh/kubecodex.git

  - git:
      files:
      - path: apps/**/testing/config_dir.yaml
      repoURL: https://github.com/TheCodingSheikh/kubecodex.git
      template:
        spec:
          source:
            directory:
              exclude: '{{ exclude }}'
              include: '{{ include }}'
              jsonnet: {}
              recurse: true
  template:
    metadata:
      name: 'testing-{{ .userGivenName }}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{ .destNamespace }}'
        server: '{{ .destServer }}'
      project: testing
      source:
        path: '{{ .srcPath }}'
        repoURL: '{{ .srcRepoURL }}'
        targetRevision: '{{ .srcTargetRevision }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
  templatePatch: |
    metadata:
      labels: {{ toYaml .labels | nindent 8 }}
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: '{{ appName }}'
      annotations: {{ toYaml .annotations | nindent 8 }}
  syncPolicy: {}