apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-incluster-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"] 